# Generated by Django 4.1.1 on 2022-09-09 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='grado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='grado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
