# Generated by Django 4.1.1 on 2022-09-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_alumno_id_grado_remove_materia_id_grado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grado',
            name='id_materia',
        ),
        migrations.AddField(
            model_name='grado',
            name='id_aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aula'),
        ),
        migrations.AddField(
            model_name='materia',
            name='id_grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.grado'),
        ),
    ]
