# Generated by Django 4.1.1 on 2022-09-10 00:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_grado_id_materia_grado_id_aula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='id_grado',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='id_profesor',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='numero_telefonico',
            new_name='materia',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='hora_de_finalizacion',
            new_name='hora',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='id_grado',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_de_inicio',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='id_materia',
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aula'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='capacidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Grado',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
