# Generated by Django 4.1.1 on 2022-09-10 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_materia_id_grado_remove_materia_id_profesor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
