# Generated by Django 4.1.1 on 2022-09-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_alumno_created_at_remove_alumno_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
