# Generated by Django 4.1.1 on 2022-09-10 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_alumno_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=35),
        ),
    ]
